export interface UserList{
    noOfProducts:number,
    userId:any,
    firstName:string,
    lastName:string,
    email:string,
    userName:string,
    phoneNumber:string,
    profileImage:string,
    fullName:string,
    address:string,
    whatsAppNumber:number,
  
}
  export interface UserProductDetails
  {
    productId: any,
    createdAt:any,
    createdBy:any,
    modifiedAt:any,
    modifiedBy:any,
    addedAgo:any,
    imageLink:string,
    isInUserWishList: false,
    sellerName:string,
    sellerProfileImage:string,
    sellerAddress: string,
    sellerCreatedAt: string,
    sellerPhoneNumber: string,
    sellerWhatsAppNumber: string,
    subCategoryName: string,
    categoryId: string,
    categoryName: string,
    productStatusId: number,
    productStatus: string,
    subCategoryId:any,
    name:string,
    description:string,
    isOld: boolean,
    howYearOld:number,
    price:number,
    location:string,
    productImages:string,
  } 
